definitions:
  environment: &environment
    vars:
      # App Details
      VERSION_NAME: $VERSION_NAME
      VERSION_CODE: $VERSION_CODE
      APP_NAME: $APP_NAME
      ORG_NAME: $ORG_NAME
      WEB_URL: $WEB_URL
      PKG_NAME: $PKG_NAME
      BUNDLE_ID: $BUNDLE_ID
      EMAIL_ID: $EMAIL_ID

      # Feature Flags
      PUSH_NOTIFY: $PUSH_NOTIFY
      IS_DEEPLINK: $IS_DEEPLINK
      IS_SPLASH: $IS_SPLASH
      IS_PULLDOWN: $IS_PULLDOWN
      IS_BOTTOMMENU: $IS_BOTTOMMENU
      IS_LOAD_IND: $IS_LOAD_IND

      # Permissions
      IS_CAMERA: $IS_CAMERA
      IS_LOCATION: $IS_LOCATION
      IS_MIC: $IS_MIC
      IS_NOTIFICATION: $IS_NOTIFICATION
      IS_CONTACT: $IS_CONTACT
      IS_BIOMETRIC: $IS_BIOMETRIC
      IS_CALENDAR: $IS_CALENDAR
      IS_STORAGE: $IS_STORAGE

      # UI Configuration
      LOGO_URL: $LOGO_URL
      SPLASH: $SPLASH
      SPLASH_BG: $SPLASH_BG
      SPLASH_BG_COLOR: $SPLASH_BG_COLOR
      SPLASH_TAGLINE: $SPLASH_TAGLINE
      SPLASH_TAGLINE_COLOR: $SPLASH_TAGLINE_COLOR
      SPLASH_ANIMATION: $SPLASH_ANIMATION
      SPLASH_DURATION: $SPLASH_DURATION

      # Bottom Menu Configuration
      BOTTOMMENU_ITEMS: $BOTTOMMENU_ITEMS
      BOTTOMMENU_BG_COLOR: $BOTTOMMENU_BG_COLOR
      BOTTOMMENU_ICON_COLOR: $BOTTOMMENU_ICON_COLOR
      BOTTOMMENU_TEXT_COLOR: $BOTTOMMENU_TEXT_COLOR
      BOTTOMMENU_ACTIVE_TAB_COLOR: $BOTTOMMENU_ACTIVE_TAB_COLOR
      BOTTOMMENU_ICON_POSITION: $BOTTOMMENU_ICON_POSITION
      BOTTOMMENU_VISIBLE_ON: $BOTTOMMENU_VISIBLE_ON

      # Firebase Configuration
      firebase_config_android: $firebase_config_android
      firebase_config_ios: $firebase_config_ios

      # iOS Certificates
      CERT_URL: $CERT_URL
      CERT_PASSWORD: $CERT_PASSWORD
      PROFILE_URL: $PROFILE_URL
      APPLE_TEAM_ID: $APPLE_TEAM_ID
      APNS_KEY_ID: $APNS_KEY_ID
      APNS_AUTH_KEY_URL: $APNS_AUTH_KEY_URL

      # Android Keystore
      KEY_STORE: $KEY_STORE
      CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
      CM_KEY_ALIAS: $CM_KEY_ALIAS
      CM_KEY_PASSWORD: $CM_KEY_PASSWORD

  scripts:
    - &debug_env
      name: Debug Environment Variables
      script: |
        echo "🔍 Checking environment variables..."
        echo "App Name: $APP_NAME"
        echo "Package Name: $PKG_NAME"
        echo "Bundle ID: $BUNDLE_ID"
        echo "Version: $VERSION_NAME ($VERSION_CODE)"
        echo "Push Notifications: $PUSH_NOTIFY"
        echo "Features enabled:"
        echo "- Splash: $IS_SPLASH"
        echo "- Deep Linking: $IS_DEEPLINK"
        echo "- Bottom Menu: $IS_BOTTOMMENU"
        echo "- Pull to Refresh: $IS_PULLDOWN"
        echo "- Loading Indicator: $IS_LOAD_IND"

    - &clean_build
      name: Clean Build
      script: |
        echo "🧹 Cleaning previous builds..."
        flutter clean
        rm -rf build
        flutter pub get

    - &setup_firebase
      name: Setup Firebase
      script: |
        if [ "$PUSH_NOTIFY" = "true" ]; then
          echo "🔥 Setting up Firebase..."
          
          # Android Setup
          if [ -n "$firebase_config_android" ]; then
            mkdir -p android/app
            curl -o android/app/google-services.json "$firebase_config_android"
            echo "✅ Firebase Android config downloaded"
          fi
          
          # iOS Setup
          if [ -n "$firebase_config_ios" ]; then
            mkdir -p ios/Runner
            curl -o ios/Runner/GoogleService-Info.plist "$firebase_config_ios"
            echo "✅ Firebase iOS config downloaded"
          fi
        else
          echo "⏭️ Skipping Firebase setup (PUSH_NOTIFY is false)"
        fi

    - &setup_android_signing
      name: Setup Android Signing
      script: |
        echo "🔐 Setting up Android signing..."
        if [ -n "$KEY_STORE" ]; then
          curl -o android/app/keystore.jks "$KEY_STORE"
          
          cat >> android/key.properties << EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_PASSWORD
        keyAlias=$CM_KEY_ALIAS
        storeFile=keystore.jks
        EOF
          echo "✅ Android signing configured"
        else
          echo "⚠️ No keystore provided"
        fi

    - &setup_ios_signing
      name: Setup iOS Signing
      script: |
        echo "🔐 Setting up iOS signing..."

        # Create keychain
        KEYCHAIN_NAME="ios-build.keychain"
        KEYCHAIN_PASSWORD="temporary"
        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
        security default-keychain -s "$KEYCHAIN_NAME"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
        security set-keychain-settings -t 3600 -u "$KEYCHAIN_NAME"

        # Download and import certificate
        if [ -n "$CERT_URL" ]; then
          curl -o certificate.p12 "$CERT_URL"
          security import certificate.p12 -k "$KEYCHAIN_NAME" -P "$CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
        fi

        # Download and setup provisioning profile
        if [ -n "$PROFILE_URL" ]; then
          curl -o profile.mobileprovision "$PROFILE_URL"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        fi

        # Download APNS key if provided
        if [ -n "$APNS_AUTH_KEY_URL" ]; then
          curl -o ios/AuthKey_${APNS_KEY_ID}.p8 "$APNS_AUTH_KEY_URL"
        fi

    - &build_apk
      name: Build APK
      script: |
        echo "📱 Building APK..."
        flutter build apk \
          --release \
          --dart-define=WEB_URL="$WEB_URL" \
          --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY" \
          --dart-define=PKG_NAME="$PKG_NAME" \
          --dart-define=APP_NAME="$APP_NAME" \
          --dart-define=ORG_NAME="$ORG_NAME" \
          --dart-define=VERSION_NAME="$VERSION_NAME" \
          --dart-define=VERSION_CODE="$VERSION_CODE" \
          --dart-define=EMAIL_ID="$EMAIL_ID" \
          --dart-define=IS_SPLASH="$IS_SPLASH" \
          --dart-define=SPLASH="$SPLASH" \
          --dart-define=SPLASH_BG="$SPLASH_BG" \
          --dart-define=SPLASH_ANIMATION="$SPLASH_ANIMATION" \
          --dart-define=SPLASH_BG_COLOR="$SPLASH_BG_COLOR" \
          --dart-define=SPLASH_TAGLINE="$SPLASH_TAGLINE" \
          --dart-define=SPLASH_TAGLINE_COLOR="$SPLASH_TAGLINE_COLOR" \
          --dart-define=SPLASH_DURATION="$SPLASH_DURATION" \
          --dart-define=IS_PULLDOWN="$IS_PULLDOWN" \
          --dart-define=LOGO_URL="$LOGO_URL" \
          --dart-define=IS_BOTTOMMENU="$IS_BOTTOMMENU" \
          --dart-define=BOTTOMMENU_ITEMS="$BOTTOMMENU_ITEMS" \
          --dart-define=BOTTOMMENU_BG_COLOR="$BOTTOMMENU_BG_COLOR" \
          --dart-define=BOTTOMMENU_ICON_COLOR="$BOTTOMMENU_ICON_COLOR" \
          --dart-define=BOTTOMMENU_TEXT_COLOR="$BOTTOMMENU_TEXT_COLOR" \
          --dart-define=BOTTOMMENU_ACTIVE_TAB_COLOR="$BOTTOMMENU_ACTIVE_TAB_COLOR" \
          --dart-define=BOTTOMMENU_ICON_POSITION="$BOTTOMMENU_ICON_POSITION" \
          --dart-define=BOTTOMMENU_VISIBLE_ON="$BOTTOMMENU_VISIBLE_ON" \
          --dart-define=IS_DEEPLINK="$IS_DEEPLINK" \
          --dart-define=IS_LOAD_IND="$IS_LOAD_IND" \
          --dart-define=IS_CAMERA="$IS_CAMERA" \
          --dart-define=IS_LOCATION="$IS_LOCATION" \
          --dart-define=IS_BIOMETRIC="$IS_BIOMETRIC" \
          --dart-define=IS_MIC="$IS_MIC" \
          --dart-define=IS_CONTACT="$IS_CONTACT" \
          --dart-define=IS_CALENDAR="$IS_CALENDAR" \
          --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION" \
          --dart-define=IS_STORAGE="$IS_STORAGE"

    - &build_aab
      name: Build App Bundle
      script: |
        echo "📦 Building App Bundle..."
        flutter build appbundle \
          --release \
          --dart-define=WEB_URL="$WEB_URL" \
          --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY" \
          --dart-define=PKG_NAME="$PKG_NAME" \
          --dart-define=APP_NAME="$APP_NAME" \
          --dart-define=ORG_NAME="$ORG_NAME" \
          --dart-define=VERSION_NAME="$VERSION_NAME" \
          --dart-define=VERSION_CODE="$VERSION_CODE" \
          --dart-define=EMAIL_ID="$EMAIL_ID" \
          --dart-define=IS_SPLASH="$IS_SPLASH" \
          --dart-define=SPLASH="$SPLASH" \
          --dart-define=SPLASH_BG="$SPLASH_BG" \
          --dart-define=SPLASH_ANIMATION="$SPLASH_ANIMATION" \
          --dart-define=SPLASH_BG_COLOR="$SPLASH_BG_COLOR" \
          --dart-define=SPLASH_TAGLINE="$SPLASH_TAGLINE" \
          --dart-define=SPLASH_TAGLINE_COLOR="$SPLASH_TAGLINE_COLOR" \
          --dart-define=SPLASH_DURATION="$SPLASH_DURATION" \
          --dart-define=IS_PULLDOWN="$IS_PULLDOWN" \
          --dart-define=LOGO_URL="$LOGO_URL" \
          --dart-define=IS_BOTTOMMENU="$IS_BOTTOMMENU" \
          --dart-define=BOTTOMMENU_ITEMS="$BOTTOMMENU_ITEMS" \
          --dart-define=BOTTOMMENU_BG_COLOR="$BOTTOMMENU_BG_COLOR" \
          --dart-define=BOTTOMMENU_ICON_COLOR="$BOTTOMMENU_ICON_COLOR" \
          --dart-define=BOTTOMMENU_TEXT_COLOR="$BOTTOMMENU_TEXT_COLOR" \
          --dart-define=BOTTOMMENU_ACTIVE_TAB_COLOR="$BOTTOMMENU_ACTIVE_TAB_COLOR" \
          --dart-define=BOTTOMMENU_ICON_POSITION="$BOTTOMMENU_ICON_POSITION" \
          --dart-define=BOTTOMMENU_VISIBLE_ON="$BOTTOMMENU_VISIBLE_ON" \
          --dart-define=IS_DEEPLINK="$IS_DEEPLINK" \
          --dart-define=IS_LOAD_IND="$IS_LOAD_IND" \
          --dart-define=IS_CAMERA="$IS_CAMERA" \
          --dart-define=IS_LOCATION="$IS_LOCATION" \
          --dart-define=IS_BIOMETRIC="$IS_BIOMETRIC" \
          --dart-define=IS_MIC="$IS_MIC" \
          --dart-define=IS_CONTACT="$IS_CONTACT" \
          --dart-define=IS_CALENDAR="$IS_CALENDAR" \
          --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION" \
          --dart-define=IS_STORAGE="$IS_STORAGE"

    - &build_ipa
      name: Build IPA
      script: |
        echo "🍎 Building IPA..."
        flutter build ipa \
          --release \
          --dart-define=WEB_URL="$WEB_URL" \
          --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY" \
          --dart-define=PKG_NAME="$PKG_NAME" \
          --dart-define=APP_NAME="$APP_NAME" \
          --dart-define=ORG_NAME="$ORG_NAME" \
          --dart-define=VERSION_NAME="$VERSION_NAME" \
          --dart-define=VERSION_CODE="$VERSION_CODE" \
          --dart-define=EMAIL_ID="$EMAIL_ID" \
          --dart-define=IS_SPLASH="$IS_SPLASH" \
          --dart-define=SPLASH="$SPLASH" \
          --dart-define=SPLASH_BG="$SPLASH_BG" \
          --dart-define=SPLASH_ANIMATION="$SPLASH_ANIMATION" \
          --dart-define=SPLASH_BG_COLOR="$SPLASH_BG_COLOR" \
          --dart-define=SPLASH_TAGLINE="$SPLASH_TAGLINE" \
          --dart-define=SPLASH_TAGLINE_COLOR="$SPLASH_TAGLINE_COLOR" \
          --dart-define=SPLASH_DURATION="$SPLASH_DURATION" \
          --dart-define=IS_PULLDOWN="$IS_PULLDOWN" \
          --dart-define=LOGO_URL="$LOGO_URL" \
          --dart-define=IS_BOTTOMMENU="$IS_BOTTOMMENU" \
          --dart-define=BOTTOMMENU_ITEMS="$BOTTOMMENU_ITEMS" \
          --dart-define=BOTTOMMENU_BG_COLOR="$BOTTOMMENU_BG_COLOR" \
          --dart-define=BOTTOMMENU_ICON_COLOR="$BOTTOMMENU_ICON_COLOR" \
          --dart-define=BOTTOMMENU_TEXT_COLOR="$BOTTOMMENU_TEXT_COLOR" \
          --dart-define=BOTTOMMENU_ACTIVE_TAB_COLOR="$BOTTOMMENU_ACTIVE_TAB_COLOR" \
          --dart-define=BOTTOMMENU_ICON_POSITION="$BOTTOMMENU_ICON_POSITION" \
          --dart-define=BOTTOMMENU_VISIBLE_ON="$BOTTOMMENU_VISIBLE_ON" \
          --dart-define=IS_DEEPLINK="$IS_DEEPLINK" \
          --dart-define=IS_LOAD_IND="$IS_LOAD_IND" \
          --dart-define=IS_CAMERA="$IS_CAMERA" \
          --dart-define=IS_LOCATION="$IS_LOCATION" \
          --dart-define=IS_BIOMETRIC="$IS_BIOMETRIC" \
          --dart-define=IS_MIC="$IS_MIC" \
          --dart-define=IS_CONTACT="$IS_CONTACT" \
          --dart-define=IS_CALENDAR="$IS_CALENDAR" \
          --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION" \
          --dart-define=IS_STORAGE="$IS_STORAGE" \
          --export-options-plist=ios/ExportOptions.plist

  artifacts:
    - &apk_artifacts build/**/outputs/**/*.apk
    - &aab_artifacts build/**/outputs/**/*.aab
    - &ipa_artifacts build/ios/ipa/*.ipa
    - &build_logs flutter_build*.log

  publishing: &email_notification
    email:
      recipients:
        - $EMAIL_ID
      notify:
        success: true
        failure: true

workflows:
  android-apk:
    name: Android APK Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - *debug_env
      - *clean_build
      - *setup_firebase
      - *setup_android_signing
      - *build_apk
    artifacts:
      - *apk_artifacts
      - *build_logs
    publishing: *email_notification

  android-aab:
    name: Android App Bundle Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - *debug_env
      - *clean_build
      - *setup_firebase
      - *setup_android_signing
      - *build_aab
    artifacts:
      - *aab_artifacts
      - *build_logs
    publishing: *email_notification

  ios:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - *debug_env
      - *clean_build
      - *setup_firebase
      - *setup_ios_signing
      - *build_ipa
    artifacts:
      - *ipa_artifacts
      - *build_logs
    publishing: *email_notification

  combined:
    name: Combined Workflow (APK, AAB, IPA)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - *debug_env
      - *clean_build
      - *setup_firebase
      - *setup_android_signing
      - *build_apk
      - *build_aab
      - *setup_ios_signing
      - *build_ipa
    artifacts:
      - *apk_artifacts
      - *aab_artifacts
      - *ipa_artifacts
      - *build_logs
    publishing: *email_notification
