name: quickappproj
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rename: ^3.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_inappwebview: ^6.0.0
#  firebase_messaging: ^15.2.2
#  firebase_core: ^3.11.0
#  flutter_native_splash: ^2.4.4
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  connectivity_plus: ^6.1.3
#  firebase_analytics: ^11.4.5
  flutter_local_notifications: ^19.0.0
  permission_handler: ^12.0.0
  path_provider: ^2.1.5
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

#flutter_native_splash:
#
#  color: "#ffffff"
#  image: "assets/images/splash.png"
#  android_gravity: fill
#  ios_content_mode: scaleAspectFit
#  fullscreen: true
#  branding: "assets/images/splash.png"
#  branding_mode: bottom
#  web: false

  android_12:
    color: "#ffffff"
    image: "assets/images/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
